### ISSUE TITLE
Support for adding derive annotations for traits outside prost?

### ISSUE THREAD

**Issue by andrew-otiv** [tokio-rs/prost#1064]
Prost already can generate types supporting Clone and PartialEq, which is great. We'd like to also be able to derive other traits, like Default, or the various traits used by fuzzers like cargo fuzz. Rust's orphan rules make this hard in the context of code generation.

We currently only have ~50 code generated types, so we could write our own impls manually, but maybe it would possible to add trait derivations to the generated code via configuration? Theres already a mechanism for switching ~off the already supported traits; I am interested in going the other direction.

Related: https://github.com/tokio-rs/prost/pull/493

**Comment by romac** [comment]
Have you tried using https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_attribute?

**Comment by andrew-otiv** [comment]
That looks very promising, thanks! We're trying to set this up from bazel rules_rust; hopefully we can drive this through keyword arguments to https://bazelbuild.github.io/rules_rust/rust_proto.html#rust_prost_library.

**Comment by caspermeijn** [comment]
You can derive any trait you want using `type_attribute` as commented earlier. For example to derive Arbirary on every protobuf type:
```rust
    prost_build::Config::new()
        .type_attribute(".", "#[derive(arbitrary::Arbitrary)]")
        .compile_protos(&["src/types.proto"], &["src/"])?;
```

If this doesn't resolve your problem, please reopen the issue.

**Comment by RazaGR** [comment]
@caspermeijn how can we path `type_attribute` when using buf.build? below doesn't work with `type_attribute`

```
version: v1
plugins:
  - plugin: prost
    out: protos/src
    opt:
      - bytes=.
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
      - type_attribute=member.User:#[derive(Serialize, Deserialize, Debug)]
```
