### ISSUE TITLE
generated code is incompatible with tonic 0.13

### ISSUE THREAD

**Issue by mikea** [tokio-rs/prost#1264]
Lost of things seem to break:

- `type alias `tonic::body::BoxBody` is private`
- varios unsatisfied trait bounds

**Comment by caspermeijn** [comment]
I don't understand what this issue is. It seems to me this is a `tonic` issue.

Could you add instructions for how to reproduce this? The best way to do that is to add a test to the `prost` codebase.

**Comment by billf** [comment]
not a prost issue.

known issue from the breaking change in https://github.com/hyperium/tonic/pull/2013

you can patch around this in `Cargo.toml`
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

```toml
[dependencies]
protoc-gen-tonic = { version = "0.4" }

[patch.crates-io]
# or make your own local fork, see "overriding dependencies" link above
protoc-gen-tonic = { git = "https://github.com/SuperFluffy/protoc-gen-prost.git", branch = "bump-tonic" }
```

and/or

```sh
# i bumped the version to 0.5 in my branch, but this simply @Superfluffy's work under the hood
cargo install --git https://github.com/billf/protoc-gen-prost.git --branch bump-tonic protoc-gen-tonic --force
```

the exact manner will depend on how you are generating code to begin with.

credit to @superfluffy https://github.com/neoeinstein/protoc-gen-prost/pull/119
