### ISSUE TITLE
"Could not find `protoc`" error from GitHub Action

### ISSUE THREAD

**Issue by Paul-Folbrecht** [tokio-rs/prost#1281]
This is not prost per se-related but I'm hoping I can get a bit of guidance.

I'm unable to get a relatively simple GitHub Action build working due to this error

`Error: Custom { kind: NotFound, error: "Could not find `protoc`. If `protoc` is installed, try setting the `PROTOC` environment variable to the path of the `protoc` binary. To install it on Debian, run `apt-get install protobuf-compiler`. It is also available at https://github.com/protocolbuffers/protobuf/releases  For more information: https://docs.rs/prost-build/#sourcing-protoc" }
`
even though I am indeed installing protoc in the build - exactly as is done in this repo's GitHub workflow, actually (I tried other methods first).

Relevant deploy.yml parts:

```
env:
  PROTOC_VERSION: "3.25.3"

jobs:
  build-test-deploy:
    # runs-on: ubuntu-24.04-arm - not yet supported for private repos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu

      - name: install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@${{ env.PROTOC_VERSION }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=aarch64-unknown-linux-gnu
```

Previously, using this install method

```
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
```

running `which protoc` and `protoc --version` in the build after the install gives expected results.

Basic build.rs:

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::compile_protos("protos/market_data.proto")?;
    tonic_build::compile_protos("protos/order.proto")?;
    Ok(())
}
```

I also tried setting protoc_executable explicitly to the confirmed path (this was when I was installing via apt-get as above):

```
    let mut prost_build = prost_build::Config::new();
    prost_build.protoc_executable("/usr/bin/protoc");
```

What am I missing?
