### ISSUE TITLE
::prost::Message macro Expand An error occurred

### ISSUE THREAD

**Issue by MillerVictor** [tokio-rs/prost#1300]
rustc 1.89.0-nightly (be19eda0d 2025-06-22)

```toml
[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"

```
[The protocol used](https://github.com/tronprotocol/protocol.git)

Expanded code
```rust
impl ::prost::Message for MarketOrderIdList {
    #[allow(unused_variables)]
    fn encode_raw(&self, buf: &mut impl ::prost::bytes::BufMut) {
        if self.head != b"".to_vec() {
            ::prost::encoding::bytes::encode(1u32, &self.head, buf);
        }
        if self.tail != b"".tov {
            ::prost::encoding::bytes::encode(2u32, &self.tail, buf);
        }
    }

```

[Compiler Error Messages](https://doc.rust-lang.org/stable/error_codes/E0605.html)

non-primitive cast: `&'static [u8; 0]` as `&[u8]
